### ISSUE TITLE
Support more providers and rename this repo to a more generic name

### ISSUE THREAD

**Issue by brunolemos** [mxstbr/micro-github#8]
So, this is a great idea, but I see no reason for it to be limited to just github.
All oauth authentication services are very similar, just the URL change.

Why not make this support Github, Google, Linkedin, Instagram, etc?
If not, some other repos [like this one ](https://github.com/hypebeast/micro-auth) will start appearing, but I believe yours should be the default one.

**Comment by brunolemos** [comment]
All right, I just made a similar thing to what I just suggested: 
https://github.com/brunolemos/micro-oauth

I tested it with GitHub and Instagram only, but I believe it now supports a lot of other oauth2 providers.

It's still not the ideal solution though, because you have to create one server for each provider.
The ideal solution in my opinion would be 1 microservice to rule them all, probably with a routing like `/auth/github`, `/auth/instagram`, ...

**Comment by brunolemos** [comment]
@adrianmcli check this https://github.com/brunolemos/micro-oauth

**Comment by mxstbr** [comment]
I don't particularly care about others and I know such a microservice exists already 😉 (I just can't remember the name)

If this is trivial enough to not bother me when just using Github I'd happily take a PR!
